### ISSUE TITLE
Equation 6 in paper

### ISSUE THREAD

**Issue by mohitnihalani** [honghaow/FORK#1]
Hi, I think there is a typo in equation 6 of the paper, shouldn't it be -ve Q value for the second predicted state instead of +ve.

**Comment by honghaow** [comment]
Yes, you are right. Thanks for pointing it out.

**Comment by mohitnihalani** [comment]
I also have one more question, in the code for bipedal-hardcore, during policy training you are calculating policy loss using target_critic, shouldn't it be critic. Did you found any issues using critic while training?

**Comment by honghaow** [comment]
There is no issue using critic, they both can work.  The reason I am using critic_target is somehow it solves the problem more quickly.
