### ISSUE TITLE
Chould you share plot codes

### ISSUE THREAD

**Issue by MohammadAsadolahi** [honghaow/FORK#2]
Hi and thank you for sharing such a genius design.
I wanted to ask how did you trained agents in parallel and how you have drawn the plots in paper
Than you

**Comment by honghaow** [comment]
Hi, I didn't train the agents parallelly, but simply open several terminals. The plots are generated using the viskit (https://github.com/vitchyr/viskit).

**Comment by MohammadAsadolahi** [comment]
thank you for answering me. I'm writing a paper on a new algorithm and I'm trying to plot the results.
I wanted to ask you did you use the average reward of the previous 100 episodes on your plots or is it the average of all previous episodes or the average of all runs of each episode?
and how many runs you have used to gather data for each algorithm? and should I use environment seeds?
best regards

**Comment by honghaow** [comment]
The reward at each point is the average across 10 different testing runs and 5 different random seeds. I recommend to use the same set of random seeds for all the algorithms you are going to test,

**Comment by MohammadAsadolahi** [comment]
Hi and thank you for answering me.
Ao every model is trained 10 run * 5seed = 50 times 
And then you have plotted the average of those 50 runs eat each step?
So you havnt used moving average of 100 previous steps?

**Comment by honghaow** [comment]
Yes. But for the moving average, I used the default setting of viskit, the sliding window size is 5.

**Comment by MohammadAsadolahi** [comment]
thank you for your time responding to me. 
wish you another dense research.
best regards
