### ISSUE TITLE
algorithm not working on mujoco Humanoid-v3

### ISSUE THREAD

**Issue by MohammadAsadolahi** [honghaow/FORK#3]
hi and thank you for your attention
I'm in the testing phase of your algorithm but I cannot get results with td3 or fork-td3 on Humanoid-v3 and I think the noise clip and other noise parameters should be tuned correctly. 
so how should I get your algorithm to work on Humanoid-v3?
by the way I'm using gym to use Humanoid-v3 enviroment

**Comment by honghaow** [comment]
Hi, I didn't do any parameter tunning on Humanoid-v3. The codes provided works well. 
I also used gym. I am not sure if it is because of the version of Mujoco. I used Mujoco 200.

**Comment by MohammadAsadolahi** [comment]
TNX for answering
Its stange because humenoid actions are in range -4 to 4
A d i cant get any result with it. 
For SAC implementation when should i use deterministic policy and when to use gaussian policy?  I mean for each env i should use deterministic SAC or FORK-SAC

**Comment by honghaow** [comment]
I recommend you to check the original SAC paper for details. People usually use a gaussian policy when using SAC.
