### ISSUE TITLE
repository provided data

### ISSUE THREAD

**Issue by MohammadAsadolahi** [honghaow/FORK#4]
Hi, Hope you doing well
the data you have provided with progress.csv has a column named: "Average Return"
I think it's "average reward" between the current step number say 25,000 and the previous step number 20,000
so you have added all rewards from 20,000 to 25,000 timesteps and then you divide it by 5000?
and at last, took an average of this "average reward" column of all 5 seeds you have information and plot it using viskit tool with default average window which is 5?

**Comment by honghaow** [comment]
The average return represents the average testing returns which means at each step (e.g. 25,000), 10 different testing instances are evaluated. That is different from the training reward, but they are at the same level.  
Yes, viskit will take care of the plotting.
