### ISSUE TITLE
DDPG implementaion?

### ISSUE THREAD

**Issue by MohammadAsadolahi** [honghaow/FORK#6]
hi mate. hope you are doing well.
i couldn't find DDPG version you've used in paper implementation. would you please direct me to DDPG implementation
best regards!

**Comment by honghaow** [comment]
Hi, sorry about the late response. I implemented the algorithm by myself. There are many useful resources on GitHub if you do not want to start from nothing. This implementation may help.  https://github.com/ghliu/pytorch-ddpg
