### ISSUE TITLE
Ambiguity in calculating whats called "Best Average Cumulative Reward" in the paper

### ISSUE THREAD

**Issue by MohammadAsadolahi** [honghaow/FORK#7]
Hello dear honghaow

The result table presented in the paper contains numbers that are called "Best Average Cumulative Reward". In the appendix section, end of page 15, you have mentioned a formula to calculate such values. But I can't figure out how those values are calculated. 

AantV3 environment, for example, we have 5 runs for TD3. And for every run we have 201 evaluation reward. How these 5 (instances) * 201 (rewards) are used to calculate "Best Average Cumulative Reward"? In Numpy, for example, how should we aggregate and divide them?

i have tried every possible way but ive failed to reproduce the exact numbers presented in the paper:

ant_results= np.array with shape of (5,201)
ant_results.max(axis=0)/201
sum(ant_results.sum(axis=0)/5)/201
and etc ...

best regards

**Comment by honghaow** [comment]
Hi Mohammad,

Sorry for the last reply. The best average cumulative is just the maximum of the mean of 5 instances. Assume we have a results for Ant-V3 with the shape of (5,201).  Then In Numpy, just try np.amax(np.mean(ant_results,axis=1)).
